import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    // ENGLISH LANGUAGE
    'en_US': {
      "select_your_language": "Select your language",
      "save": "Save",
      "cancel": "Cancel",
      "choose_a_language": "Choose a language",
      "language": "English",
      "send": "Send",
      "upload_image": "Upload image",
      "settings": "Settings",
      "general": "General",
      "dark_theme": "Dark Theme",
      "set_dark_theme": "Set dark theme",
      "notifications": "Notifications",
      "receive_push_notification": "Receive Push Notification",
      "upvote": "Upvote to your post",
      "answer": "Answer to your post",
      "posts": "Popular Posts",
      "information": "Information about my crops",
      "logout": "Logout",
      "home": "Home",
      "profile": "Profile",
      "change_language": "Change Language",
      "message": "Messages",
      "privacy_policy": "Privacy Policy",
      "terms_and_conditions": "Terms and Conditions",
      "send_feedback": "Send Feedback",
      "help": "Help",
      "share": "Share",
      "history": "History",
      "about_us": "About Us",
      "welcome_back": "Welcome back.",
      "login_subtitle": "Discover Limitless Choices and Unmatched Convenience",
      "email": "Email",
      "password": "Password",
      "remember_me": "Remember Me",
      "forgot_password": "Forgot Password",
      "sign_in": "Sign In",
      "create_account": "Create Account",
      "upload_your _crop_image": "Upload your crop image",
      "analyze_it_and_detect_the_crop_diseases": "Analyze it and detect the crop diseases",
      "see_the_result": "See the result",
      "on_boarding_sub_title_1": "Welcome to the world of Artificial Intelligence - Your Perfect Assistant Awaits!",
      "on_boarding_sub_title_2": "For Classification of Crop Diseases easily and Effectiveness, Diagnosis and Recommendation",
      "on_boarding_sub_title_3": "From old technology to advanced, simple and time-saving",
      "skip": "Skip",
      "forgot_password_sub_title": "Don't worry sometimes people can forget too, enter your email and we will send you a password reset link.",
      "submit": "Submit",
      "change_password_sub_title": "Your Account Security is Our Priority! We've sent you a secure Link to safely change your Password and keep your Account Protected",
      "done": "Done",
      "resend_email": "Resend Email",
      "signup_title": "Let's create your account",
      "first_name": "First Name",
      "last_name": "Last Name",
      "username": "Username",
      "phone_number": "Phone Number",
      "new_password": "New Password",
      "i_agree_to": "I agree to",
      "and": "and",
      "terms_of_use": "Terms of use",
      "confirm_email": "verify your email address",
      "confirm_email_sub_title": "Congratulation! Your Account Awaits: Verify your Email to start use and experience a world of AI",
      "continue": "Continue",
      "change_name": "Change Name",
      "change_name_heading": "Use real name for easy verification. This name will appear on several pages.",
      "change_phone_number": "Change Phone Number",
      "change_phone_number_heading": "Use real phone number for easy verification. This phone number will appear on several pages.",
      "change_profile_picture": "Change Profile Picture",
      "profile_information": "Profile Details",
      "name": "Name",
      "personal_information": "Personal Information",
      "user_id": "User ID",
      "delete_account": "Delete Account",
      "feedback": "FeedBack",
      "feedback_heading": "We will appreciate to receive your feedback for our App improvements.",
      "ask_community": "Ask Community",
      "ask_community_heading": "Improve the probability of receiving the right answer",
      "select_crop": "Select Crop",
      "add_question": "Add a question...",
      "describe_question": "Describe your question...",
      "your_location": "Your location",
      "change_image": "Change Image",
      "beans": "Beans",
      "maize": "Maize",
      "cassava": "Cassava",
      "rice": "Rice",
      "error": "Error",
      "no_data": "No community posts available",
      "something_went_wrong": "Something went wrong",
      "no_replies_found": "No replies found",
      "community": "Community",
      "search": "Search by crop type or location",
      "filter_by": "Filter by",
      "apply_filter": "Apply Filter",
      "crop_categories": "Crop categories",
      "beans_disease_detector": "Beans Disease Detector",
      "result": "Result",
      "accuracy": "Accuracy",
      "can't_identify": "Can't identify",
      "take_a_photo": "Take A Photo",
      "pick_from_gallery": "Pick from Gallery",
      "cassava_disease_detector": "Cassava Disease Detector",
      "plant_diseases_detector": "Plant Diseases Detector",
      "detector": "Detector",
      "detector_title": "Identify your crop's diseases in a\nfew seconds",
      "detector_sub_title": "Quickly identify the exact problem\nwithin your crop.",
      "start_diagnosis": "Start Diagnosis",
      "disease_details": "Disease Details",
      "no_disease_details_available": "No disease details available for ",
      "symptoms": "Symptoms",
      "causes": "Causes",
      "treatments": "Treatments",
      "maize_disease_detector": "Maize Disease Detector",
      "recommendations": "Recommendations",
      "rice_disease_detector": "Rice Disease Detector",
      "kilimo_app": "Kilimo App",
      "or_sign_in_with": "or Sign in with",
      "or_sign_up_with": "or Sign up with",
      "weather_forecast": "Weather Forecast",
      "wind_speed": "Wind speed",
      "next_4_days": "Next 4 days",
      "pro-tip": "Pro-tip",
      "bad_day": "Today would be a bad day for: APPLYING PESTICIDES",
      "good_day": "Today would be a good day for: APPLYING PESTICIDES",
      "raining_until_tomorrow": "Raining until tomorrow",
      "no_rain_is_forecast_this_week": "No rain is forecasted this week",
      "maize_descriptions": "The three leaf rusts on maize are common rust, polysora rust, and tropical rust. The disease is found worldwide in subtropical, temperate, and highland environments with high humidity. Common rust is most conspicuous when plants approach tasseling.",
      "beans_descriptions": "There are two widespread bacterial blights that affect most types of beans, common blight (Xanthomonas campestris pv phaseoli) and halo blight (Pseudomonas syringae pathovar phaseolicola). The stems, leaves and fruits of bean plants can be infected by either disease.",
      "rice_descriptions": "Bacterial leaf blight (BLB) disease alone can cause up to 50% yield losses worldwide. Rice yields can also be significantly impacted by some diseases like brown spot (BS) and leaf smut (LSm). One of the most common diseases affecting rice is BS, caused by Drechsleraoryzae.",
      "cassava_descriptions": "According to the different characteristics, cassava disease can bemainly classified into Cassava Bacterial Blight (CBB), Cassava Brown Streak Disease (CBSD), Cassava Green Mottle (CGM), Cassava Mosaic Disease (CMD), etc., which can lead to reduced and/or diseased cassava output.",
      "network_problem": "Network Problem",
      "cultivation_tips": "Cultivation Tips",
      "see_relavant_information_on": "See Relavant Information on",
      "by_task": "By Task",
      "by_stage": "By Stage",
      "plant_selection": "Plant Selection",
      "planting": "Planting",
      "plant_training": "Plant Training",
      "monitoring": "Monitoring",
      "site_selection": "Site Selection",
      "field_preparation": "Field Preparation",
      "weeding": "Weeding",
      "integration": "Integration",
      "fertilizer_chemical": "Fertilizer Chemical",
      "preventive_measure": "Preventive Measure",
      "harvesting": "Harvesting",
      "post_harvest": "Post Harvest",
      "by_stage_title": "Choose the date your sowing was done or planned.",
      "add_sowing_date_to_start": "Add sowing date to start",
      "fertilizer_calculator": "Fertilizer Calculator",
      "crop_disease_detector": "Crop Disease Detector",
      "resources": "Resources",
      "reply_hint": "Reply...",
      "reply_label": "Write your reply",
      "see_relevant_information_on": "See relevant information on",
      "crop_title": "Select your crop",
      "nutrient_quantities": "Nutrient quantities",
      "nitrogen": "Nitrogen (N) in kg/ha",
      "phosphorus": "Phosphorus (P) in kg/ha",
      "potassium": "Potassium (K) in kg/ha",
      "plot_size": "Plot size",
      "fertilizer_subtitle": "Sizes smaller than one unit are expressed as 0.\nExample: half acre = 0.5",
      "plot_size_label": "Plot Size (hectares)",
      "calculate": "Calculate",
      "view_history": "View History",
      "calculation_history": "Calculation History",
      "resource_1": "Fertilizer\nCalculator",
      "resource_2": "Pests &\nDiseases",
      "resource_3": "Cultivation\nTips",
      "resource_4": "Pest &\nDisease\nAlert",
      "pest_and_diseases": "Pest & diseases",
      "disease_by_stage": "Disease By Stage",
      "disease_subtitle": "All pests and diseases that might appear in\nyour crop at different stages",
      "seeding_stage": "Seeding Stage",
      "see_more": "See More",
      "vegetative_stage": "Vegetative Stage",
      "flowering_stage": "Flowering Stage",
      "fruiting_stage": "Fruiting Stage",
      "harvesting_stage": "Harvesting Stage",
      "pest_and_disease_alert": "Pest and Disease Alert",
      "pest_and_disease_alert_subtitle": "Currently, there are no pests or diseases reported in your vicinity.",
      "prevention_tips": "Prevention Tips",
      "field_monitoring": "Field Monitoring",
      "field_monitoring_subtitle": "Catch early and prevent the build-up of fatal pests in your field.",
      "learn_more": "Learn More",
      "field_monitoring_description": "Field monitoring is the most effective practice to detect plant diseases at an early stage. Detecting diseases earlier will give you enough time to prevent them from spreading and further harming your crops.",
      "why_monitoring": "Why is monitoring important?",
      "monitoring_field_help": "Monitoring your field regularly helps you:",
      "help_1": "Save money on expensive treatments.",
      "help_2": "Minimize yield loss.",
      "info": "Farmers who regularly monitor their field achieve up to 50% higher yields.",
      "how_to_monitor": "How to monitor your field:",
      "visit_your_field": "Visiting your field",
      "how_1": "We recommend doing this at least\ntwo times per week.",
      "check_several_spots": "Check several spots",
      "how_2": "Make sure to check at least 5\ndifferent parts of your field, as the\nillustration shows below.",
      "step_3": "Look for unusual patterns and\nactivities in each of these spots",
      "how_3": "Pay attention to discolouration,\ndeformation, feeding damages, and\nother insect activities.",
      "carefully_examine_the_entire_crop": "Carefully examine the entire crop",
      "how_4": "Don't forget to check the leaves\nfrom both sides, the stems, buds,\nfruits, and shoots.",
      "take_action_if_you_spot_something": "Take action if you spot something",
      "take_action_subtitle": "When you find signs of an infestation, make sure to use our crop diagnosis feature to identify the disease and treat it efficiently.",
      "addition_description": "For addition support, reach out to the Kilimo App Community or consult your trusted local advisor.",
      "beans_disease_detection": "Beans Disease Detection",
      "cassava_disease_detection": "Cassava Disease Detection",
      "maize_disease_detection": "Maize Disease Detection",
      "rice_disease_detection": "Rice Disease Detection",
      "preventive_measures": "Preventive Measures",
      "prediction": "Crop Disease Forecasting Using Weather Information",
      "report": "Report",
      "snapshot_error": "Somthing went wrong!. Please try again later.",
      "enter_your_email": "Enter your email",
      "enter_your_password": "Enter your password",
      "farmer": "Farmer",
      "extension_officer": "Extension Officer",
      "enter_your_first_name": "Enter your first name",
      "enter_your_last_name": "Enter your last name",
      "enter_your_username": "Enter your username",
      "enter_your_phonenumber": "Enter your phone number",
      "select_a_role": "Please select a role",
      "country": "Country",
      "state": "State",
      "city": "City",
      "select_country": "Select Country",
      "select_state": "Select State",
      "select_city": "Select City",
      "role": "Role",
      "district": "District",
      "ward": "Ward",
      "full_name": "Full Name",
      "enter_district": "Enter District",
      "enter_ward": "Enter Ward",
      "maize_description": "Maize is a cereal grain that was first domesticated by indigenous peoples in southern Mexico about 10,000 years ago. The leafy stalk of the plant produces pollen inflorescences and separate ovuliferous inflorescences called ears that yield kernels or seeds, which are fruits.",
      "maize_planting": "Maize is a warm-season crop, it should be planted when the soil temperature is between 60-95°F. The ideal soil temperature for germination is 86°F. Maize is a heavy feeder and requires a lot of nutrients. It is recommended to plant maize in a well-drained soil with a pH of 6.0-7.0.",
      "maize_harvesting": "Maize is ready for harvest when the kernels are hard and the husks are dry. The best way to determine if maize is ready for harvest is to check the moisture content of the kernels. The moisture content should be between 20-25%. Maize can be harvested by hand or by using a combine harvester.",
      "storage": "Storage",
      "maize_storage_description": "Maize should be stored in a cool, dry place to prevent mold growth. The ideal storage temperature for maize is between 50-60°F. Maize should be stored in a well-ventilated area to prevent moisture buildup. Maize can be stored in airtight containers or in a silo.",
      "pest_and_disease": "Pests and Diseases",
      "maize_pest_and_disease_description": "Maize is susceptible to a number of pests and diseases. Some common pests that affect maize include corn earworm, cutworm, and corn borer. Some common diseases that affect maize include gray leaf spot, northern corn leaf blight, and common rust. It is important to monitor maize for pests and diseases and take appropriate action to control them.",
      "common_problem": "Common Problems",
      "maize_common_problem_description": "Maize is susceptible to a number of problems, including poor germination, poor pollination, and poor kernel development. Poor germination can be caused by planting maize in cold, wet soil. Poor pollination can be caused by planting maize in hot, dry weather. Poor kernel development can be caused by planting maize in poor soil or by not providing enough nutrients. It is important to monitor maize for problems and take appropriate action to correct them.",
      "beans_description": "Beans are a warm-season crop that grows best at temperatures between 70 and 80°F. Beans are a great source of protein, fiber, and vitamins. They are easy to grow and can be grown in a variety of soil types. Beans are a great crop for beginners and experienced gardeners alike.",
      "beans_planting_description": "Beans should be planted in well-drained soil that receives full sun. Beans can be planted directly in the garden or started indoors and transplanted. Beans should be planted in rows with 18 inches between plants. Beans should be watered regularly and mulched to retain moisture.",
      "beans_harvesting_description": "Beans should be harvested when the pods are plump and the seeds are tender. Beans should be picked regularly to encourage more growth. Beans should be harvested in the morning when the pods are cool. Beans should be stored in a cool, dry place.",
      "beans_storage": "Beans should be stored in a cool, dry place. Beans should be stored in a paper bag or a perforated plastic bag. Beans should be stored away from direct sunlight. Beans should be stored in a well-ventilated area.",
      "beans_pest_and_disease_description": "Beans are susceptible to a variety of pests and diseases. Beans should be inspected regularly for signs of pests and diseases. Beans should be treated with insecticides and fungicides as needed. Beans should be planted in well-drained soil to prevent root rot.",
      "beans_common_problem_description": "Beans are susceptible to a variety of problems, including poor germination, poor growth, and poor yield. Beans should be planted in well-drained soil to prevent problems. Beans should be watered regularly and mulched to retain moisture. Beans should be inspected regularly for signs of problems.",
      "rice_description": "Rice is the seed of the grass species Oryza sativa (Asian rice) or less commonly Oryza glaberrima (African rice). As a cereal grain, it is the most widely consumed staple food for a large part of the world's human population, especially in Asia and Africa. It is the agricultural commodity with the third-highest worldwide production, after sugarcane and maize.",
      "rice_planting_description": "Rice is best grown in flooded fields, though it can also be grown in dry fields. The water helps to control weeds, but it also provides the rice with nutrients. The rice plant is an annual grass that produces round, edible grains. The rice plant can grow to 1–1.8 m (3.3–5.9 ft) tall, occasionally more depending on the variety and soil fertility.",
      "rice_harvesting_description": "Rice is harvested when the grains have a moisture content of about 25%. The rice is then threshed to separate the grains from the stalks. The grains are then dried to a moisture content of about 14% before being stored or milled. Rice can be stored for long periods of time without spoiling, making it an important food source for many people around the world.",
      "rice_storage_description": "Rice should be stored in a cool, dry place to prevent spoilage. It should be stored in airtight containers to prevent insects and rodents from getting into it. Rice can be stored for long periods of time without spoiling, making it an important food source for many people around the world.",
      "pest_and_disease_description": "Rice is susceptible to a number of pests and diseases. Some of the most common pests include the rice weevil, the rice moth, and the rice bug. Some of the most common diseases include rice blast, sheath blight, and bacterial leaf blight. These pests and diseases can cause significant damage to rice crops, so it is important to monitor them closely and take steps to control them when necessary.",
      "common_problem_description": "Rice is susceptible to a number of problems, including nutrient deficiencies, waterlogging, and lodging. Nutrient deficiencies can cause the leaves of the rice plant to turn yellow and die. Waterlogging can cause the roots of the rice plant to rot. Lodging can cause the rice plant to fall over, reducing yield. It is important to monitor rice crops closely for signs of problems and take steps to correct them when necessary.",
      "cassava_description": "Cassava is a major staple crop in Africa, Asia and Latin America. It is a major source of carbohydrates and is grown for its edible root. Cassava is a major source of carbohydrates and is grown for its edible root.",
      "cassava_planting_description": "Cassava is propagated by planting stem cuttings. The cuttings are usually 15-30 cm long and 2.5-5 cm in diameter. The cuttings are planted in furrows or ridges, 10-20 cm deep. The cuttings are planted at an angle of 45 degrees, with the upper end of the cutting planted upwards. The cuttings are planted at a spacing of 1 m x 1 m. The cuttings are planted in rows, with a spacing of 1 m between rows. The cuttings are planted in rows, with a spacing of 1 m between rows. The cuttings are planted in rows, with a spacing of 1 m between rows.",
      "cassava_harvesting_description": "Cassava is harvested by uprooting the entire plant. The roots are then separated from the stems. The roots are then washed and peeled. The roots are then cut into pieces and dried. The dried roots are then ground into flour. The flour is then used to make a variety of food products, such as bread, cakes, biscuits, and noodles.",
      "cassava_storage_description": "Cassava roots can be stored for up to 3 months. The roots should be stored in a cool, dry place. The roots should be stored in a well-ventilated place. The roots should be stored in a place that is free from pests and diseases. The roots should be stored in a place that is free from pests and diseases. The roots should be stored in a place that is free from pests and diseases.",
      "cassava_pest_and_disease_description": "Cassava is susceptible to a number of pests and diseases. The most common pests are the cassava mealybug, the cassava green mite, and the cassava whitefly. The most common diseases are cassava mosaic disease, cassava brown streak disease, and cassava bacterial blight. The most common pests are the cassava mealybug, the cassava green mite, and the cassava whitefly. The most common diseases are cassava mosaic disease, cassava brown streak disease, and cassava bacterial blight.",
      "cassava_common_problem_description": "The cassava green mite (Mononychellus tanajoa) is a major pest of cassava plants, particularly in Africa. These tiny pests suck the sap from the leaves, causing them to turn yellow and become distorted. Severe infestations can lead to defoliation and a significant reduction in yield.",
      "upload_image_for_detection": "Upload an image to detect crop diseases.",
      "coming_soon": "Coming soon...",
      "total_farmer": "Total Farmers",
      "total_case": "Total Cases",
      "compared_to_last_week": "Compared to last week",
      "compared_to_last_7_week": "Compared to last 7 days",
      "weekly_cases": "Weekly Cases",
      "recent_cases": "Recent Cases",
      "case_id": "Case ID",
      "crop_type": "Crop Type",
      "date": "Date",
      "results": "Results",
      "cases_by_crop_type": "Cases By Crop Type",
      "cases": "Cases",
      "percentage": "Percentage",
      "agrovet": "Agrovet",
      "agrovet_title": "Empower Farmers by Connecting Trusted Agrovet Suppliers!",
      "agrovet_hint": "Enter agrovet name",
      "enter_phone_number": "Enter Phone Number",
      "recommendation": "Recommendation",
      "recommendation_heading": "Guide Farmers with Effective Solutions for Healthy Crops!",
      "disease_name": "Enter disease name",
      "disease_symptoms": "Enter disease symptoms",
      "enter_treatment": "Enter Treatment",
      "enter_preventive_measures": "Enter preventive measures",
      "reports": "Reports",
      "crop_disease_report": "Crop diseases report",
      "role_not_set": "Role not set",
      "please_contact_admin": "Please contact admin",
    },
    
    // SWAHILI LANGUAGE
    'sw_TZ': {
      "select_your_language": "Chagua lugha yako",
      "save": "Hifadhi",
      "cancel": "Batilisha",
      "choose_a_language": "Chagua lugha",
      "language": "Swahili",
      "send": "Tuma",
      "upload_image": "Pakia picha",
      "settings": "Vipimo",
      "general": "Jumla",
      "dark_theme": "Mandhari ya Giza",
      "set_dark_theme": "Weka mandhari ya giza",
      "notifications": "Taarifa",
      "receive_push_notification": "Pokea arifa ya kushinikiza",
      "upvote": "Upvote kwa post yako",
      "answer": "Jibu kwa chapisho lako",
      "posts": "Machapisho maarufu",
      "information": "Taarifa kuhusu mazao yangu",
      "logout": "Toka",
      "home": "Nyumbani",
      "profile": "Umbo",
      "change_language": "Badilisha Lugha",
      "message": "Ujumbe",
      "privacy_policy": "Sera ya faragha",
      "terms_and_conditions": "Vigezo na Masharti",
      "send_feedback": "Tuma Maoni",
      "help": "Kusaidia",
      "share": "Kushiriki",
      "history": "Historia",
      "about_us": "Kutuhusu",
      "welcome_back": "Karibu tena.",
      "login_subtitle": "Gundua Chaguzi zisizo na kikomo na Urahisi usiolingana",
      "email": "Barua pepe",
      "password": "Nywila",
      "remember_me": "Nikumbuke",
      "forgot_password": "Umesahau Nywila",
      "sign_in": "Ingia ndani",
      "create_account": "Unda Akaunti",
      "upload_your_crop_image": "Pakia picha yako ya mazao",
      "analyze_it_and_detect_the_crop_diseases": "Chunguza na kugundua magonjwa ya mimea",
      "see_the_result": "Angalia matokeo",
      "on_boarding_sub_title_1": "Karibu kwenye ulimwengu wa Akili bandia - Msaidizi wako Kamili Anasubiri!",
      "on_boarding_sub_title_2": "Kwa Uainishaji wa Magonjwa ya Mazao kwa urahisi na ufanisi, Utambuzi na Mapendekezo",
      "on_boarding_sub_title_3": "Kutoka teknolojia ya zamani hadi ya juu, rahisi na inayookoa wakati",
      "skip": "Ruka",
      "forgot_password_sub_title": "Usijali wakati mwingine watu wanaweza kusahau pia, ingiza barua pepe yako na tutakutumia kiungo cha kuweka upya nenosiri.",
      "submit": "Wasilisha",
      "change_password_sub_title": "Usalama wa akaunti yako ni kipaumbele chetu! Tumekutumia kiungo salama ili kubadilisha nywila yako kwa usalama na kuweka Akaunti yako Salama",
      "done": "Kufanyika",
      "resend_email": "Tuma tena",
      "signup_title": "Fungua akaunti yako",
      "first_name": "Jina la kwanza",
      "last_name": "Jina la Mwisho",
      "username": "Jina la mtumiaji",
      "phone_number": "Nambari ya Simu",
      "new_password": "Nywila Mpya",
      "i_agree_to": "Nakubaliana na",
      "and": "na",
      "terms_of_use": "Masharti",
      "confirm_email": "Thibitisha anwani yako ya barua pepe",
      "confirm_email_sub_title": "Hongera! Akaunti yako Inasubiri: Thibitisha Barua pepe yako kuanza kutumia na uzoefu ulimwengu wa AI",
      "continue": "Endelea",
      "change_name": "Badilisha Jina",
      "change_name_heading": "Tumia jina halisi kwa uthibitishaji rahisi. Jina hili litaonekana kwenye kurasa kadhaa.",
      "change_phone_number": "Badilisha Nambari ya Simu",
      "change_phone_number_heading": "Tumia nambari halisi ya simu kwa uthibitishaji rahisi. Nambari hii ya simu itaonekana kwenye kurasa kadhaa.",
      "change_profile_picture": "Badilisha Picha ya Wasifu",
      "profile_information": "Maelezo ya Wasifu",
      "name": "Jina",
      "personal_information": "Maelezo ya kibinafsi",
      "user_id": "Kitambulisho cha Mtumiaji",
      "delete_account": "Futa Akaunti",
      "feedback": "Maoni",
      "feedback_heading": "Tutathamini kupokea maoni yako kwa maboresho yetu ya Programu.",
      "ask_community": "Uliza Jamii",
      "ask_community_heading": "Kuboresha uwezekano wa kupata jibu sahihi",
      "select_crop": "Mazao",
      "add_question": "Weka swali...",
      "describe_question": "Elezea swali lako...",
      "your_location": "Mahali pako",
      "change_image": "Badilisha Picha",
      "beans": "Maharage",
      "maize": "Mahindi",
      "cassava": "Mihogo",
      "rice": "Mpunga",
      "error": "Kosa",
      "no_data": "Hakuna machapisho ya jamii yanayopatikana",
      "something_went_wrong": "Kuna kitu kilienda vibaya",
      "no_replies_found": "Hakuna majibu yaliyopatikana",
      "community": "Jamii",
      "search": "Tafuta kwa aina ya mazao au eneo",
      "filter_by": "Chuja kwa",
      "apply_filter": "Tumia Kichujio",
      "crop_categories": "Makundi ya mazao",
      "beans_disease_detector": "Kigunduzi cha Magonjwa ya Maharage",
      "result": "Matokeo",
      "accuracy": "Usahihi",
      "can't_identify": "Haiwezi kutambua",
      "take_a_photo": "Piga picha",
      "pick_from_gallery": "Chagua kutoka kwa Matunzio",
      "cassava_disease_detector": "Kigunduzi cha Magonjwa ya Muhogo",
      "plant_diseases_detector": "Kigunduzi cha Magonjwa ya Mimea",
      "detector": "Kigunduzi",
      "detector_title": "Tambua magonjwa ya mimea yako kwa sekunde chache",
      "detector_sub_title": "Tambua haraka tatizo halisi ndani ya mazao yako.",
      "start_diagnosis": "Anza Utambuzi",
      "disease_details": "Maelezo ya Magonjwa",
      "no_disease_details_available": "Hakuna maelezo ya ugonjwa yanayopatikana",
      "symptoms": "Dalili",
      "causes": "Sababu",
      "treatments": "Matibabu",
      "maize_disease_detector": "Kigunduzi cha Magonjwa ya Mahindi",
      "recommendations": "Mapendekezo",
      "rice_disease_detector": "Kigunduzi cha Magonjwa ya Mchele",
      "kilimo_app": "Kilimo App",
      "or_sign_in_with": "au kuingia kwa",
      "or_sign_up_with": "au jiandikishe kwa",
      "weather_forecast": "Utabiri wa hali ya hewa",
      "wind_speed": "Kasi ya upepo",
      "next_4_days": "Siku 4 zifuatazo",
      "pro-tip": "Vidokezo",
      "bad_day": "Leo itakuwa siku mbaya kwa: KUTUMIA PESTICIDES",
      "good_day": "Leo itakuwa siku nzuri kwa ajili ya: KUTUMIA PESTICIDES",
      "raining_until_tomorrow": "Mvua mpaka kesho",
      "no_rain_is_forecast_this_week": "Hakuna mvua inayotarajiwa wiki hii",
      "maize_descriptions": "kutu tatu za majani kwenye mahindi ni kutu ya kawaida, kutu ya polysora, na kutu ya kitropiki. Ugonjwa huu hupatikana duniani kote katika mazingira ya chini ya tropiki, kiasi, na nyanda za juu na unyevu wa juu. kutu ya kawaida ni ya kupendeza zaidi wakati mimea inakaribia kuonja.",
      "beans_descriptions": "Kuna blights mbili za bakteria zilizoenea ambazo huathiri aina nyingi za maharagwe, blight ya kawaida (Xanthomonas campestris pv phaseoli) na halo blight (Pseudomonas syringae pathovar phaseolicola). Majani, majani na matunda ya mimea ya maharagwe yanaweza kuambukizwa na ugonjwa wowote.",
      "rice_descriptions": "Ugonjwa wa blight ya majani ya bakteria (BLB) peke yake inaweza kusababisha hadi 50% hasara ya mavuno duniani kote. Mazao ya mpunga pia yanaweza kuathiriwa sana na magonjwa mengine kama vile doa la kahawia (BS) na smut ya jani (LSm). Moja ya magonjwa ya kawaida yanayoathiri mchele ni BS, unaosababishwa na Drechsleraoryzae.",
      "cassava_descriptions": "Kwa mujibu wa sifa tofauti, ugonjwa wa muhogo unaweza kuainishwa hasa katika Blight ya Cassava Bacterial (CBB), Magonjwa ya Mihogo Brown Streak (CBSD), Cassava Green Mottle (CGM), Magonjwa ya Muhogo (CMD), nk, ambayo inaweza kusababisha kupungua na / au magonjwa ya muhogo.",
      "network_problem": "Tatizo la Mtandao",
      "cultivation_tips": "Vidokezo vya Kilimo",
      "see_relavant_information_on": "Angalia taarifa muhimu juu ya",
      "by_task": "Kwa Kazi",
      "by_stage": "Kwa Hatua",
      "plant_selection": "Uteuzi wa Mimea",
      "planting": "Kupanda",
      "plant_training": "Mafunzo ya mimea",
      "monitoring": "Ufuatiliaji",
      "site_selection": "Uteuzi wa Shamba",
      "field_preparation": "Maandalizi ya shamba",
      "weeding": "Kupalilia",
      "integration": "Ushirikiano",
      "fertilizer_chemical": "Kemikali ya mbolea",
      "preventive_measure": "Hatua ya Kuzuia",
      "harvesting": "Kuvuna",
      "post_harvest": "Baada ya mavuno",
      "by_stage_title": "Chagua tarehe ambayo kupanda kwako kulifanywa au kupangwa.",
      "add_sowing_date_to_start": "Ongeza tarehe ya kupanda",
      "fertilizer_calculator": "Kikokotoo Cha Mbolea",
      "crop_disease_detector": "Kigunduzi cha Magonjwa\nya Mazao",
      "resources": "Rasilimali",
      "reply_hint": "Jibu...",
      "reply_label": "Andika majibu yako",
      "see_relevant_information_on": "Angalia taarifa muhimu",
      "crop_title": "Chagua mazao yako",
      "nutrient_quantities": "Kiasi cha virutubishi",
      "nitrogen": "Nitrojeni (N) katika kilo/ha",
      "phosphorus": "Phosphorus (P) katika kilo/ha",
      "potassium": "Potassium (K) katika kilo/h",
      "plot_size": "Ukubwa wa ploti",
      "fertilizer_subtitle": "Ukubwa mdogo kuliko kitengo kimoja\nunaonyeshwa kama Mfano:\nnusu ya ekari = 0.5",
      "plot_size_label": "Ukubwa wa Plot (hekta)",
      "calculate": "Kokotoa",
      "view_history": "Tazama Historia",
      "calculation_history": "Historia ya Hesabu",
      "resource_1": "Kikokotoo\nCha\nMbolea",
      "resource_2": "Vidudu\nna\nMagonjwa",
      "resource_3": "Vidokezo\nvya Kilimo",
      "resource_4": "Tahadhari\nya wadudu\nna\nmagonjwa",
      "pest_and_diseases": "Wadudu na magonjwa",
      "disease_by_stage": "Ugonjwa kwa Hatua",
      "disease_subtitle": "Wadudu na magonjwa yote ambayo yanaweza\nkuonekana katika mazao yako\nkatika hatua tofauti",
      "seeding_stage": "Hatua ya Kuona",
      "see_more": "Tazama Zaidi",
      "vegetative_stage": "Hatua ya Mboga",
      "flowering_stage": "Hatua ya Maua",
      "fruiting_stage": "Hatua ya Matunda",
      "harvesting_stage": "Hatua ya Uvunaji",
      "pest_and_disease_alert": "Tahadhari ya wadudu na magonjwa",
      "pest_and_disease_alert_subtitle": "Kwa sasa, hakuna wadudu au magonjwa yaliyoripotiwa katika eneo lako.",
      "prevention_tips": "Vidokezo vya Kuzuia",
      "field_monitoring": "Ufuatiliaji wa Uga",
      "field_monitoring_subtitle": "Kukamata mapema na kuzuia kujenga-up ya wadudu mbaya katika shamba lako.",
      "learn_more": "Jifunze zaidi",
      "field_monitoring_description": "Ufuatiliaji wa shamba ni mazoezi bora zaidi ya kugundua magonjwa ya mimea katika hatua ya mapema. Kugundua magonjwa mapema kutakupa muda wa kutosha kuwazuia kuenea na kuharibu mazao yako zaidi.",
      "why_monitoring": "Kwa nini ufuatiliaji ni muhimu?",
      "monitoring_field_help": "Kufuatilia shamba lako mara kwa mara hukusaidia:",
      "help_1": "Kuokoa fedha kwa matibabu ya gharama kubwa.",
      "help_2": "Punguza hasara ya mavuno.",
      "info": "Wakulima ambao hufuatilia shamba lao mara kwa mara hufikia mavuno ya juu ya 50%.",
      "how_to_monitor": "Jinsi ya kufuatilia shamba lako:",
      "visit_your_field": "Tembelea uwanja wako",
      "how_1": "Tunapendekeza kufanya hivyo angalau\nmara mbili kwa wiki.",
      "check_several_spots": "Angalia matangazo kadhaa",
      "how_2": "Hakikisha uangalie angalau sehemu 5\ntofauti za shamba lako, kama\nkielelezo kinavyoonyesha hapa chini.",
      "step_3": "Tafuta mifumo isiyo ya kawaida\nna shughuli katika kila\nmoja ya maeneo haya",
      "how_3": "Zingatia rangi, deformation,\nuharibifu wa kulisha, na\nshughuli zingine za wadudu.",
      "carefully_examine_the_entire_crop": "Chunguza kwa makini mazao yote",
      "how_4": "Usisahau kuangalia majani\nkutoka pande zote mbili, shina, buds,\nmatunda, na shina.",
      "take_action_if_you_spot_something": "Chukua hatua ikiwa unaona kitu.",
      "take_action_subtitle": "Unapopata dalili za uvamizi, hakikisha kutumia kipengele chetu cha utambuzi wa mazao ili kutambua ugonjwa na kutibu kwa ufanisi.",
      "addition_description": "Kwa msaada zaidi, fikia Jumuiya ya Programu ya Kilimo au wasiliana na mshauri wako wa ndani anayeaminika.",
      "beans_disease_detection": "Utambuzi wa Magonjwa ya Maharage",
      "cassava_disease_detection": "Utambuzi wa Magonjwa ya Muhogo",
      "maize_disease_detection": "Utambuzi wa Magonjwa ya Mahindi",
      "rice_disease_detection": "Utambuzi wa Magonjwa ya Mpunga",
      "preventive_measures": "Hatua za kuzuia",
      "prediction": "Utabiri wa Magonjwa ya Mazao Kutumia Taarifa ya Hali ya Hewa",
      "report": "Ripoti",
      "snapshot_error": "Kuna tatizo la mfumo! Tafadhali jaribu tena baadaye.",
      "enter_your_email": "Ingiza barua pepe yako",
      "enter_your_password": "Ingiza nywila yako",
      "farmer": "Mkulima",
      "extension_officer": "Afisa wa ugani",
      "enter_your_first_name": "Ingiza jina lako la kwanza",
      "enter_your_last_name": "Ingiza jina lako la mwisho",
      "enter_your_username": "Ingiza jina lako la mtumiaji",
      "enter_your_phonenumber": "Ingiza nambari yako ya simu",
      "select_a_role": "Tafadhali chagua nafasi",
      "country": "Nchi",
      "state": "Jimbo",
      "city": "Mji",
      "select_country": "Chagua Nchi",
      "select_state": "Chagua Jimbo",
      "select_city": "Chagua Mji",
      "role": "Jukumu",
      "district": "Wilaya",
      "ward": "Kata",
      "full_name": "Jina Kamili",
      "enter_district": "Ingiza Wilaya",
      "enter_ward": "Ingiza Kata",
      "maize_description": "Mahindi ni nafaka ya nafaka ambayo ilifugwa kwa mara ya kwanza na watu wa asili kusini mwa Mexico karibu miaka 10,000 iliyopita. Stalk ya majani ya mmea hutoa inflorescences ya poleni na inflorescences tofauti za ovuliferous inayoitwa masikio ambayo hutoa kernels au mbegu, ambazo ni matunda.",
      "maize_planting": "Mahindi ni zao la msimu wa joto, linapaswa kupandwa wakati joto la udongo ni kati ya 60-95 ° F.  Joto bora la udongo kwa kuota ni 86 ° F. Mahindi ni chakula kizito na kinahitaji virutubisho vingi. Inashauriwa kupanda mahindi katika udongo uliosafishwa vizuri na pH ya 6.0-7.0.",
      "maize_harvesting": "Mahindi yako tayari kwa mavuno wakati punje ni ngumu na husks ni kavu. Njia bora ya kuamua ikiwa mahindi yako tayari kwa mavuno ni kuangalia maudhui ya unyevu wa kernels. Kiwango cha unyevu kinapaswa kuwa kati ya 20-25%. Mahindi yanaweza kuvunwa kwa mkono au kwa kutumia mvunaji mchanganyiko.",
      "storage": "Hifadhi",
      "maize_storage_description": "Mahindi yanapaswa kuhifadhiwa katika sehemu ya baridi na kavu ili kuzuia ukuaji wa ukungu. Joto bora la kuhifadhi mahindi ni kati ya 50-60 ° F. Mahindi yanapaswa kuhifadhiwa katika eneo lenye hewa safi ili kuzuia unyevu. Mahindi yanaweza kuhifadhiwa kwenye vyombo vya hewa au kwenye silo.",
      "pest_and_disease": "Vidudu na Magonjwa",
      "maize_pest_and_disease_description": "Mahindi huathirika na wadudu na magonjwa kadhaa. Baadhi ya wadudu wa kawaida wanaoathiri mahindi ni pamoja na mdudu wa mahindi, mdudu wa kukata, na mzaaji wa mahindi. Baadhi ya magonjwa ya kawaida yanayoathiri mahindi ni pamoja na jani la kijivu, blight ya majani ya mahindi ya kaskazini, na kutu ya kawaida. Ni muhimu kufuatilia mahindi kwa wadudu na magonjwa na kuchukua hatua stahiki za kuyadhibiti.",
      "common_problem": "Matatizo ya kawaida",
      "maize_common_problem_description": "Mahindi yanakabiliwa na matatizo kadhaa, ikiwa ni pamoja na kuota vibaya, uchafuzi duni, na maendeleo duni ya kernel. Kuota vibaya kunaweza kusababishwa na kupanda mahindi katika udongo baridi, mvua. Uchafuzi duni unaweza kusababishwa na kupanda mahindi katika hali ya hewa ya joto, kavu. Maendeleo duni ya kernel yanaweza kusababishwa na kupanda mahindi katika udongo duni au kwa kutotoa virutubisho vya kutosha. Ni muhimu kufuatilia mahindi kwa matatizo na kuchukua hatua stahiki kuyarekebisha.",
      "beans_description": "Maharagwe ni zao la msimu wa joto ambalo hukua vizuri kwa joto kati ya 70 na 80 ° F.  Maharagwe ni chanzo kikubwa cha protini, nyuzi, na vitamini. Ni rahisi kukua na inaweza kukua katika aina mbalimbali za udongo. Maharagwe ni mazao mazuri kwa Kompyuta na wakulima wenye uzoefu sawa.",
      "beans_planting_description": "Maharagwe yanapaswa kupandwa katika udongo ulio na maji mengi ambayo hupokea jua kamili. Maharagwe yanaweza kupandwa moja kwa moja kwenye bustani au kuanza ndani ya nyumba na kupandikizwa. Maharagwe yanapaswa kupandwa katika safu na inchi 18 kati ya mimea. Maharagwe yanapaswa kunyunyiziwa maji mara kwa mara na kusafishwa ili kuhifadhi unyevu.",
      "beans_harvesting_description": "Maharagwe yanapaswa kuvunwa wakati maganda ni plump na mbegu ni laini. Maharagwe yanapaswa kuchukuliwa mara kwa mara ili kuhamasisha ukuaji zaidi. Maharagwe yanapaswa kuvunwa asubuhi wakati pods ni baridi. Maharagwe yanapaswa kuhifadhiwa katika sehemu ya baridi na kavu.",
      "beans_storage": "Maharagwe yanapaswa kuhifadhiwa katika sehemu ya baridi na kavu. Maharagwe yanapaswa kuhifadhiwa kwenye mfuko wa karatasi au mfuko wa plastiki uliokatwa. Maharagwe yanapaswa kuhifadhiwa mbali na jua moja kwa moja. Maharagwe yanapaswa kuhifadhiwa katika eneo lenye hewa nzuri.",
      "beans_pest_and_disease_description": "Maharagwe huathiriwa na wadudu na magonjwa mbalimbali. Maharagwe yanapaswa kuchunguzwa mara kwa mara kwa dalili za wadudu na magonjwa. Maharagwe yanapaswa kutibiwa na wadudu na fungicides kama inahitajika. Maharagwe yanapaswa kupandwa katika udongo ulio na maji vizuri ili kuzuia kuoza kwa mizizi.",
      "beans_common_problem_description": "Maharage huathirika na matatizo mbalimbali, ikiwa ni pamoja na kuota vibaya, ukuaji duni, na mavuno duni. Maharagwe yanapaswa kupandwa katika udongo ulio na maji mengi ili kuzuia matatizo. Maharagwe yanapaswa kunyunyiziwa maji mara kwa mara na kusafishwa ili kuhifadhi unyevu. Maharagwe yanapaswa kukaguliwa mara kwa mara kwa dalili za matatizo.",
      "rice_description": "Mchele ni mbegu ya aina ya nyasi Oryza sativa (Mchele wa Asian) au chini ya kawaida Oryza glaberrima (mchele wa Kiafrika). Kama nafaka ya nafaka, ni chakula kikuu kinachotumiwa sana kwa sehemu kubwa ya idadi ya watu duniani, haswa Asia na Afrika. Ni zao la kilimo lenye uzalishaji wa tatu kwa ukubwa duniani, baada ya miwa na mahindi.",
      "rice_planting_description": "Mchele hupandwa vizuri katika mashamba yaliyofurika, ingawa inaweza pia kupandwa katika mashamba kavu. Maji husaidia kudhibiti magugu, lakini pia hutoa mchele na virutubisho. Mmea wa mchele ni nyasi ya kila mwaka ambayo hutoa nafaka za mviringo, za chakula. Mmea wa mpunga unaweza kukua hadi urefu wa mita 1-1.8 (futi 3.3-5.9), mara kwa mara zaidi kulingana na aina na rutuba ya udongo.",
      "rice_harvesting_description": "Mchele huvunwa wakati nafaka zina unyevu wa karibu 25%. Mchele huo hukatwa ili kutenganisha nafaka kutoka kwa mabua. Kisha nafaka hukaushwa kwa unyevu wa karibu 14% kabla ya kuhifadhiwa au kusaga. Mchele unaweza kuhifadhiwa kwa muda mrefu bila kuharibika, na kuifanya kuwa chanzo muhimu cha chakula kwa watu wengi duniani kote.",
      "rice_storage_description": "Mchele unapaswa kuhifadhiwa katika sehemu ya baridi, kavu ili kuzuia uharibifu. Inapaswa kuhifadhiwa katika vyombo vya hewa ili kuzuia wadudu na panya kuingia ndani yake. Mchele unaweza kuhifadhiwa kwa muda mrefu bila kuharibika, na kuifanya kuwa chanzo muhimu cha chakula kwa watu wengi duniani kote.",
      "pest_and_disease_description": "Mchele huathiriwa na wadudu na magonjwa kadhaa. Baadhi ya wadudu wa kawaida ni pamoja na weevil ya mchele, nondo ya mchele, na mdudu wa mchele. Baadhi ya magonjwa ya kawaida ni pamoja na mlipuko wa mchele, blight ya sheath, na blight ya majani ya bakteria. Wadudu hawa na magonjwa yanaweza kusababisha uharibifu mkubwa kwa mazao ya mpunga, hivyo ni muhimu kuwafuatilia kwa karibu na kuchukua hatua za kuwadhibiti pale inapobidi.",
      "common_problem_description": "Mchele huathiriwa na matatizo kadhaa, ikiwa ni pamoja na upungufu wa virutubisho, maji ya maji, na makaazi. Upungufu wa virutubishi unaweza kusababisha majani ya mmea wa mpunga kugeuka njano na kufa. Kunyunyizia maji kunaweza kusababisha mizizi ya mmea wa mchele kuoza. Makazi yanaweza kusababisha mmea wa mchele kuanguka, kupunguza mavuno. Ni muhimu kufuatilia mazao ya mpunga kwa karibu kwa dalili za matatizo na kuchukua hatua za kuyarekebisha pale inapobidi.",
      "cassava_description": "Muhogo ni zao kuu barani Afrika, Asia na Amerika ya Kusini. Ni chanzo kikuu cha wanga na hupandwa kwa mizizi yake ya chakula. Muhogo ni chanzo kikuu cha wanga na hupandwa kwa mizizi yake ya chakula.",
      "cassava_planting_description": "Muhogo huenezwa kwa kupanda vipandikizi vya shina. Vipandikizi huwa na urefu wa cm 15-30 na kipenyo cha cm 2.5-5. Vipandikizi hupandwa kwenye mifereji au matuta, kina cha cm 10-20. Vipandikizi hupandwa kwa pembe ya digrii 45, na mwisho wa juu wa kukata hupandwa juu. Vipandikizi hupandwa kwa umbali wa 1 m x 1 m. Vipandikizi hupandwa kwa safu, na nafasi ya m 1 kati ya safu. Vipandikizi hupandwa kwa safu, na nafasi ya m 1 kati ya safu. Vipandikizi hupandwa kwa safu, na nafasi ya m 1 kati ya safu.",
      "cassava_harvesting_description": "Muhogo huvunwa kwa kung'oa mmea mzima. Kisha mizizi hutenganishwa na shina. Kisha mizizi huoshwa na kusafishwa. Kisha mizizi hukatwa vipande vipande na kukaushwa. Kisha mizizi iliyokaushwa husagwa kuwa unga. Kisha unga huo hutumiwa kutengeneza vyakula mbalimbali, kama vile mkate, keki, biskuti, na tambi.",
      "cassava_storage_description": "Mizizi ya muhogo inaweza kuhifadhiwa hadi miezi 3. Mizizi inapaswa kuhifadhiwa mahali pa baridi, kavu. Mizizi inapaswa kuhifadhiwa mahali penye uingizaji hewa mzuri. Mizizi inapaswa kuhifadhiwa mahali pasipo na wadudu na magonjwa. Mizizi inapaswa kuhifadhiwa mahali pasipo na wadudu na magonjwa. Mizizi inapaswa kuhifadhiwa mahali pasipo na wadudu na magonjwa.",
      "cassava_pest_and_disease_description": "Muhogo hushambuliwa na idadi ya wadudu na magonjwa. Wadudu waharibifu wa kawaida zaidi ni mealybug ya muhogo, mite ya kijani ya muhogo, na whitefly ya mihogo. Magonjwa ya kawaida ni ugonjwa wa mosaic ya muhogo, ugonjwa wa michirizi ya kahawia ya mihogo, na ugonjwa wa bakteria wa muhogo. Wadudu waharibifu wa kawaida zaidi ni mealybug ya muhogo, mite ya kijani ya muhogo, na whitefly ya mihogo. Magonjwa ya kawaida ni ugonjwa wa mosaic ya muhogo, ugonjwa wa michirizi ya kahawia ya mihogo, na ugonjwa wa bakteria wa muhogo.",
      "cassava_common_problem_description": "Utitiri wa kijani kibichi (Mononychellus tanajoa) ni wadudu waharibifu wakuu wa mimea ya muhogo, haswa barani Afrika. Wadudu hawa wadogo hunyonya utomvu kutoka kwa majani, na kuwafanya kugeuka manjano na kupotoshwa. Maambukizi makubwa yanaweza kusababisha uharibifu wa majani na kupunguza kwa kiasi kikubwa mavuno.",
      "upload_image_for_detection": "Pakia picha ili kugundua magonjwa ya mazao.",
      "coming_soon": "Inakuja hivi karibuni...",
      "total_farmer": "Jumla ya Wakulima",
      "total_case": "Jumla ya Kesi",
      "compared_to_last_week": "Ikilinganishwa na wiki iliyopita",
      "compared_to_last_7_week": "Ikilinganishwa na siku 7 zilizopita",
      "weekly_cases": "Kesi za Wiki",
      "recent_cases": "Kesi za Hivi Punde",
      "case_id": "Kitambulisho cha kesi",
      "crop_type": "Aina ya Mazao",
      "date": "Tarehe",
      "results": "Matokeo",
      "cases_by_crop_type": "Kesi Kwa Aina ya Mazao",
      "cases": "Kesi",
      "percentage": "Asilimia",
      "agrovet": "Agrovet",
      "agrovet_title": "Wawezeshe Wakulima kwa Kuunganisha Wauzaji wa Agrovet Wanaoaminika!",
      "agrovet_hint": "Ingiza jina la agrovet",
      "enter_phone_number": "Weka Nambari ya Simu",
      "recommendation": "Pendekezo",
      "recommendation_heading": "Waelekeze Wakulima kwa Suluhu Muhimu kwa Mazao Yenye Afya!",
      "disease_name": "Ingiza jina la ugonjwa",
      "disease_symptoms": "Ingiza dalili za ugonjwa",
      "enter_treatment": "Ingiza matibabu",
      "enter_preventive_measures": "Ingiza hatua za kuzuia",
      "reports": "Ripoti",
      "crop_disease_report": "Ripoti ya magonjwa ya mazao",
      "role_not_set": "Jukumu halijawekwa",
      "please_contact_admin": "Tafadhali wasiliana na msimamizi",
   }
  };
}
