import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    // ENGLISH LANGUAGE
    'en_US': {
      "select_your_language": "Select your language",
      "save": "Save",
      "cancel": "Cancel",
      "choose_a_language": "Choose a language",
      "language": "English",
      "send": "Send",
      "upload_image": "Upload image",
      "settings": "Settings",
      "general": "General",
      "dark_theme": "Dark Theme",
      "set_dark_theme": "Set dark theme",
      "notifications": "Notifications",
      "receive_push_notification": "Receive Push Notification",
      "upvote": "Upvote to your post",
      "answer": "Answer to your post",
      "posts": "Popular Posts",
      "information": "Information about my crops",
      "logout": "Logout",
      "home": "Home",
      "profile": "Profile",
      "change_language": "Change Language",
      "message": "Messages",
      "privacy_policy": "Privacy Policy",
      "terms_and_conditions": "Terms and Conditions",
      "send_feedback": "Send Feedback",
      "help": "Help",
      "share": "Share",
      "history": "History",
      "about_us": "About Us",
      "welcome_back": "Welcome back.",
      "login_subtitle": "Discover Limitless Choices and Unmatched Convenience",
      "email": "Email",
      "password": "Password",
      "remember_me": "Remember Me",
      "forgot_password": "Forgot Password",
      "sign_in": "Sign In",
      "create_account": "Create Account",
      "upload_your _crop_image": "Upload your crop image",
      "analyze_it_and_detect_the_crop_diseases": "Analyze it and detect the crop diseases",
      "see_the_result": "See the result",
      "on_boarding_sub_title_1": "Welcome to the world of Artificial Intelligence - Your Perfect Assistant Awaits!",
      "on_boarding_sub_title_2": "For Classification of Crop Diseases easily and Effectiveness, Diagnosis and Recommendation",
      "on_boarding_sub_title_3": "From old technology to advanced, simple and time-saving",
      "skip": "Skip",
      "forgot_password_sub_title": "Don't worry sometimes people can forget too, enter your email and we will send you a password reset link.",
      "submit": "Submit",
      "change_password_sub_title": "Your Account Security is Our Priority! We've sent you a secure Link to safely change your Password and keep your Account Protected",
      "done": "Done",
      "resend_email": "Resend Email",
      "signup_title": "Let's create your account",
      "first_name": "First Name",
      "last_name": "Last Name",
      "username": "Username",
      "phone_number": "Phone Number",
      "new_password": "New Password",
      "i_agree_to": "I agree to",
      "and": "and",
      "terms_of_use": "Terms of use",
      "confirm_email": "verify your email address",
      "confirm_email_sub_title": "Congratulation! Your Account Awaits: Verify your Email to start use and experience a world of AI",
      "continue": "Continue",
      "change_name": "Change Name",
      "change_name_heading": "Use real name for easy verification. This name will appear on several pages.",
      "change_phone_number": "Change Phone Number",
      "change_phone_number_heading": "Use real phone number for easy verification. This phone number will appear on several pages.",
      "change_profile_picture": "Change Profile Picture",
      "profile_information": "Profile Details",
      "name": "Name",
      "personal_information": "Personal Information",
      "user_id": "User ID",
      "delete_account": "Delete Account",
      "feedback": "FeedBack",
      "feedback_heading": "We will appreciate to receive your feedback for our App improvements.",
      "ask_community": "Ask Community",
      "ask_community_heading": "Improve the probability of receiving the right answer",
      "select_crop": "Select Crop",
      "add_question": "Add a question...",
      "describe_question": "Describe your question...",
      "your_location": "Your location",
      "change_image": "Change Image",
      "beans": "Beans",
      "maize": "Maize",
      "cassava": "Cassava",
      "rice": "Rice",
      "error": "Error",
      "no_data": "No community posts available",
      "something_went_wrong": "Something went wrong",
      "no_replies_found": "No replies found",
      "community": "Community",
      "search": "Search by crop type or location",
      "filter_by": "Filter by",
      "apply_filter": "Apply Filter",
      "crop_categories": "Crop categories",
      "beans_disease_detector": "Beans Disease Detector",
      "result": "Result",
      "accuracy": "Accuracy",
      "can't_identify": "Can't identify",
      "take_a_photo": "Take A Photo",
      "pick_from_gallery": "Pick from Gallery",
      "cassava_disease_detector": "Cassava Disease Detector",
      "plant_diseases_detector": "Plant Diseases Detector",
      "detector": "Detector",
      "detector_title": "Identify your crop's diseases in a\nfew seconds",
      "detector_sub_title": "Quickly identify the exact problem\nwithin your crop.",
      "start_diagnosis": "Start Diagnosis",
      "disease_details": "Disease Details",
      "no_disease_details_available": "No disease details available for ",
      "symptoms": "Symptoms",
      "causes": "Causes",
      "treatments": "Treatments",
      "maize_disease_detector": "Maize Disease Detector",
      "recommendations": "Recommendations",
      "rice_disease_detector": "Rice Disease Detector",
      "kilimo_app": "Kilimo App",
      "or_sign_in_with": "or Sign in with",
      "or_sign_up_with": "or Sign up with",
      "weather_forecast": "Weather Forecast",
      "wind_speed": "Wind speed",
      "next_4_days": "Next 4 days",
      "pro-tip": "Pro-tip",
      "bad_day": "Today would be a bad day for: APPLYING PESTICIDES",
      "good_day": "Today would be a good day for: APPLYING PESTICIDES",
      "raining_until_tomorrow": "Raining until tomorrow",
      "no_rain_is_forecast_this_week": "No rain is forecasted this week",
      "maize_descriptions": "The three leaf rusts on maize are common rust, polysora rust, and tropical rust. The disease is found worldwide in subtropical, temperate, and highland environments with high humidity. Common rust is most conspicuous when plants approach tasseling.",
      "beans_descriptions": "There are two widespread bacterial blights that affect most types of beans, common blight (Xanthomonas campestris pv phaseoli) and halo blight (Pseudomonas syringae pathovar phaseolicola). The stems, leaves and fruits of bean plants can be infected by either disease.",
      "rice_descriptions": "Bacterial leaf blight (BLB) disease alone can cause up to 50% yield losses worldwide. Rice yields can also be significantly impacted by some diseases like brown spot (BS) and leaf smut (LSm). One of the most common diseases affecting rice is BS, caused by Drechsleraoryzae.",
      "cassava_descriptions": "According to the different characteristics, cassava disease can bemainly classified into Cassava Bacterial Blight (CBB), Cassava Brown Streak Disease (CBSD), Cassava Green Mottle (CGM), Cassava Mosaic Disease (CMD), etc., which can lead to reduced and/or diseased cassava output.",
      "network_problem": "Network Problem",
      "cultivation_tips": "Cultivation Tips",
      "see_relavant_information_on": "See Relavant Information on",
      "by_task": "By Task",
      "by_stage": "By Stage",
      "plant_selection": "Plant Selection",
      "planting": "Planting",
      "plant_training": "Plant Training",
      "monitoring": "Monitoring",
      "site_selection": "Site Selection",
      "field_preparation": "Field Preparation",
      "weeding": "Weeding",
      "integration": "Integration",
      "fertilizer_chemical": "Fertilizer Chemical",
      "preventive_measure": "Preventive Measure",
      "harvesting": "Harvesting",
      "post_harvest": "Post Harvest",
      "by_stage_title": "Choose the date your sowing was done or planned.",
      "add_sowing_date_to_start": "Add sowing date to start",
      "fertilizer_calculator": "Fertilizer Calculator",
      "crop_disease_detector": "Crop Disease Detector",
      "resources": "Resources",
      "reply_hint": "Reply...",
      "reply_label": "Write your reply",
      "see_relevant_information_on": "See relevant information on",
      "crop_title": "Select your crop",
      "nutrient_quantities": "Nutrient quantities",
      "nitrogen": "Nitrogen (N) in kg/ha",
      "phosphorus": "Phosphorus (P) in kg/ha",
      "potassium": "Potassium (K) in kg/ha",
      "plot_size": "Plot size",
      "fertilizer_subtitle": "Sizes smaller than one unit are expressed as 0.\nExample: half acre = 0.5",
      "plot_size_label": "Plot Size (hectares)",
      "calculate": "Calculate",
      "view_history": "View History",
      "calculation_history": "Calculation History",
      "resource_1": "Fertilizer\nCalculator",
      "resource_2": "Pests &\nDiseases",
      "resource_3": "Cultivation\nTips",
      "resource_4": "Pest &\nDisease\nAlert",
      "pest_and_diseases": "Pest & diseases",
      "disease_by_stage": "Disease By Stage",
      "disease_subtitle": "All pests and diseases that might appear in\nyour crop at different stages",
      "seeding_stage": "Seeding Stage",
      "see_more": "See More",
      "vegetative_stage": "Vegetative Stage",
      "flowering_stage": "Flowering Stage",
      "fruiting_stage": "Fruiting Stage",
      "harvesting_stage": "Harvesting Stage",
      "pest_and_disease_alert": "Pest and Disease Alert",
      "pest_and_disease_alert_subtitle": "Currently, there are no pests or diseases reported in your vicinity.",
      "prevention_tips": "Prevention Tips",
      "field_monitoring": "Field Monitoring",
      "field_monitoring_subtitle": "Catch early and prevent the build-up of fatal pests in your field.",
      "learn_more": "Learn More",
      "field_monitoring_description": "Field monitoring is the most effective practice to detect plant diseases at an early stage. Detecting diseases earlier will give you enough time to prevent them from spreading and further harming your crops.",
      "why_monitoring": "Why is monitoring important?",
      "monitoring_field_help": "Monitoring your field regularly helps you:",
      "help_1": "Save money on expensive treatments.",
      "help_2": "Minimize yield loss.",
      "info": "Farmers who regularly monitor their field achieve up to 50% higher yields.",
      "how_to_monitor": "How to monitor your field:",
      "visit_your_field": "Visiting your field",
      "how_1": "We recommend doing this at least\ntwo times per week.",
      "check_several_spots": "Check several spots",
      "how_2": "Make sure to check at least 5\ndifferent parts of your field, as the\nillustration shows below.",
      "step_3": "Look for unusual patterns and\nactivities in each of these spots",
      "how_3": "Pay attention to discolouration,\ndeformation, feeding damages, and\nother insect activities.",
      "carefully_examine_the_entire_crop": "Carefully examine the entire crop",
      "how_4": "Don't forget to check the leaves\nfrom both sides, the stems, buds,\nfruits, and shoots.",
      "take_action_if_you_spot_something": "Take action if you spot something",
      "take_action_subtitle": "When you find signs of an infestation, make sure to use our crop diagnosis feature to identify the disease and treat it efficiently.",
      "addition_description": "For addition support, reach out to the Kilimo App Community or consult your trusted local advisor.",
      "beans_disease_detection": "Beans Disease Detection",
      "cassava_disease_detection": "Cassava Disease Detection",
      "maize_disease_detection": "Maize Disease Detection",
      "rice_disease_detection": "Rice Disease Detection",
      "preventive_measures": "Preventive Measures",
      "prediction": "Crop Disease Forecasting Using Weather Information",
      "report": "Report",
    },
    
    // SWAHILI LANGUAGE
    'sw_TZ': {
      "select_your_language": "Chagua lugha yako",
      "save": "Hifadhi",
      "cancel": "Batilisha",
      "choose_a_language": "Chagua lugha",
      "language": "Swahili",
      "send": "Tuma",
      "upload_image": "Pakia picha",
      "settings": "Vipimo",
      "general": "Jumla",
      "dark_theme": "Mandhari ya Giza",
      "set_dark_theme": "Weka mandhari ya giza",
      "notifications": "Taarifa",
      "receive_push_notification": "Pokea arifa ya kushinikiza",
      "upvote": "Upvote kwa post yako",
      "answer": "Jibu kwa chapisho lako",
      "posts": "Machapisho maarufu",
      "information": "Taarifa kuhusu mazao yangu",
      "logout": "Toka",
      "home": "Nyumbani",
      "profile": "Umbo",
      "change_language": "Badilisha Lugha",
      "message": "Ujumbe",
      "privacy_policy": "Sera ya faragha",
      "terms_and_conditions": "Vigezo na Masharti",
      "send_feedback": "Tuma Maoni",
      "help": "Kusaidia",
      "share": "Kushiriki",
      "history": "Historia",
      "about_us": "Kutuhusu",
      "welcome_back": "Karibu tena.",
      "login_subtitle": "Gundua Chaguzi zisizo na kikomo na Urahisi usiolingana",
      "email": "Barua pepe",
      "password": "Nywila",
      "remember_me": "Nikumbuke",
      "forgot_password": "Umesahau Nywila",
      "sign_in": "Ingia ndani",
      "create_account": "Unda Akaunti",
      "upload_your_crop_image": "Pakia picha yako ya mazao",
      "analyze_it_and_detect_the_crop_diseases": "Chunguza na kugundua magonjwa ya mimea",
      "see_the_result": "Angalia matokeo",
      "on_boarding_sub_title_1": "Karibu kwenye ulimwengu wa Akili bandia - Msaidizi wako Kamili Anasubiri!",
      "on_boarding_sub_title_2": "Kwa Uainishaji wa Magonjwa ya Mazao kwa urahisi na ufanisi, Utambuzi na Mapendekezo",
      "on_boarding_sub_title_3": "Kutoka teknolojia ya zamani hadi ya juu, rahisi na inayookoa wakati",
      "skip": "Ruka",
      "forgot_password_sub_title": "Usijali wakati mwingine watu wanaweza kusahau pia, ingiza barua pepe yako na tutakutumia kiungo cha kuweka upya nenosiri.",
      "submit": "Wasilisha",
      "change_password_sub_title": "Usalama wa akaunti yako ni kipaumbele chetu! Tumekutumia kiungo salama ili kubadilisha nywila yako kwa usalama na kuweka Akaunti yako Salama",
      "done": "Kufanyika",
      "resend_email": "Tuma tena",
      "signup_title": "Fungua akaunti yako",
      "first_name": "Jina la kwanza",
      "last_name": "Jina la Mwisho",
      "username": "Jina la mtumiaji",
      "phone_number": "Nambari ya Simu",
      "new_password": "Nywila Mpya",
      "i_agree_to": "Nakubaliana na",
      "and": "na",
      "terms_of_use": "Masharti",
      "confirm_email": "Thibitisha anwani yako ya barua pepe",
      "confirm_email_sub_title": "Hongera! Akaunti yako Inasubiri: Thibitisha Barua pepe yako kuanza kutumia na uzoefu ulimwengu wa AI",
      "continue": "Endelea",
      "change_name": "Badilisha Jina",
      "change_name_heading": "Tumia jina halisi kwa uthibitishaji rahisi. Jina hili litaonekana kwenye kurasa kadhaa.",
      "change_phone_number": "Badilisha Nambari ya Simu",
      "change_phone_number_heading": "Tumia nambari halisi ya simu kwa uthibitishaji rahisi. Nambari hii ya simu itaonekana kwenye kurasa kadhaa.",
      "change_profile_picture": "Badilisha Picha ya Wasifu",
      "profile_information": "Maelezo ya Wasifu",
      "name": "Jina",
      "personal_information": "Maelezo ya kibinafsi",
      "user_id": "Kitambulisho cha Mtumiaji",
      "delete_account": "Futa Akaunti",
      "feedback": "Maoni",
      "feedback_heading": "Tutathamini kupokea maoni yako kwa maboresho yetu ya Programu.",
      "ask_community": "Uliza Jamii",
      "ask_community_heading": "Kuboresha uwezekano wa kupata jibu sahihi",
      "select_crop": "Mazao",
      "add_question": "Weka swali...",
      "describe_question": "Elezea swali lako...",
      "your_location": "Mahali pako",
      "change_image": "Badilisha Picha",
      "beans": "Maharage",
      "maize": "Mahindi",
      "cassava": "Mihogo",
      "rice": "Mpunga",
      "error": "Kosa",
      "no_data": "Hakuna machapisho ya jamii yanayopatikana",
      "something_went_wrong": "Kuna kitu kilienda vibaya",
      "no_replies_found": "Hakuna majibu yaliyopatikana",
      "community": "Jamii",
      "search": "Tafuta kwa aina ya mazao au eneo",
      "filter_by": "Chuja kwa",
      "apply_filter": "Tumia Kichujio",
      "crop_categories": "Makundi ya mazao",
      "beans_disease_detector": "Kigunduzi cha Magonjwa ya Maharage",
      "result": "Matokeo",
      "accuracy": "Usahihi",
      "can't_identify": "Haiwezi kutambua",
      "take_a_photo": "Piga picha",
      "pick_from_gallery": "Chagua kutoka kwa Matunzio",
      "cassava_disease_detector": "Kigunduzi cha Magonjwa ya Muhogo",
      "plant_diseases_detector": "Kigunduzi cha Magonjwa ya Mimea",
      "detector": "Kigunduzi",
      "detector_title": "Tambua magonjwa ya mimea yako kwa sekunde chache",
      "detector_sub_title": "Tambua haraka tatizo halisi ndani ya mazao yako.",
      "start_diagnosis": "Anza Utambuzi",
      "disease_details": "Maelezo ya Magonjwa",
      "no_disease_details_available": "Hakuna maelezo ya ugonjwa yanayopatikana",
      "symptoms": "Dalili",
      "causes": "Sababu",
      "treatments": "Matibabu",
      "maize_disease_detector": "Kigunduzi cha Magonjwa ya Mahindi",
      "recommendations": "Mapendekezo",
      "rice_disease_detector": "Kigunduzi cha Magonjwa ya Mchele",
      "kilimo_app": "Kilimo App",
      "or_sign_in_with": "au kuingia kwa",
      "or_sign_up_with": "au jiandikishe kwa",
      "weather_forecast": "Utabiri wa hali ya hewa",
      "wind_speed": "Kasi ya upepo",
      "next_4_days": "Siku 4 zifuatazo",
      "pro-tip": "Vidokezo",
      "bad_day": "Leo itakuwa siku mbaya kwa: KUTUMIA PESTICIDES",
      "good_day": "Leo itakuwa siku nzuri kwa ajili ya: KUTUMIA PESTICIDES",
      "raining_until_tomorrow": "Mvua mpaka kesho",
      "no_rain_is_forecast_this_week": "Hakuna mvua inayotarajiwa wiki hii",
      "maize_descriptions": "kutu tatu za majani kwenye mahindi ni kutu ya kawaida, kutu ya polysora, na kutu ya kitropiki. Ugonjwa huu hupatikana duniani kote katika mazingira ya chini ya tropiki, kiasi, na nyanda za juu na unyevu wa juu. kutu ya kawaida ni ya kupendeza zaidi wakati mimea inakaribia kuonja.",
      "beans_descriptions": "Kuna blights mbili za bakteria zilizoenea ambazo huathiri aina nyingi za maharagwe, blight ya kawaida (Xanthomonas campestris pv phaseoli) na halo blight (Pseudomonas syringae pathovar phaseolicola). Majani, majani na matunda ya mimea ya maharagwe yanaweza kuambukizwa na ugonjwa wowote.",
      "rice_descriptions": "Ugonjwa wa blight ya majani ya bakteria (BLB) peke yake inaweza kusababisha hadi 50% hasara ya mavuno duniani kote. Mazao ya mpunga pia yanaweza kuathiriwa sana na magonjwa mengine kama vile doa la kahawia (BS) na smut ya jani (LSm). Moja ya magonjwa ya kawaida yanayoathiri mchele ni BS, unaosababishwa na Drechsleraoryzae.",
      "cassava_descriptions": "Kwa mujibu wa sifa tofauti, ugonjwa wa muhogo unaweza kuainishwa hasa katika Blight ya Cassava Bacterial (CBB), Magonjwa ya Mihogo Brown Streak (CBSD), Cassava Green Mottle (CGM), Magonjwa ya Muhogo (CMD), nk, ambayo inaweza kusababisha kupungua na / au magonjwa ya muhogo.",
      "network_problem": "Tatizo la Mtandao",
      "cultivation_tips": "Vidokezo vya Kilimo",
      "see_relavant_information_on": "Angalia taarifa muhimu juu ya",
      "by_task": "Kwa Kazi",
      "by_stage": "Kwa Hatua",
      "plant_selection": "Uteuzi wa Mimea",
      "planting": "Kupanda",
      "plant_training": "Mafunzo ya mimea",
      "monitoring": "Ufuatiliaji",
      "site_selection": "Uteuzi wa Shamba",
      "field_preparation": "Maandalizi ya shamba",
      "weeding": "Kupalilia",
      "integration": "Ushirikiano",
      "fertilizer_chemical": "Kemikali ya mbolea",
      "preventive_measure": "Hatua ya Kuzuia",
      "harvesting": "Kuvuna",
      "post_harvest": "Baada ya mavuno",
      "by_stage_title": "Chagua tarehe ambayo kupanda kwako kulifanywa au kupangwa.",
      "add_sowing_date_to_start": "Ongeza tarehe ya kupanda",
      "fertilizer_calculator": "Kikokotoo Cha Mbolea",
      "crop_disease_detector": "Kigunduzi cha Magonjwa\nya Mazao",
      "resources": "Rasilimali",
      "reply_hint": "Jibu...",
      "reply_label": "Andika majibu yako",
      "see_relevant_information_on": "Angalia taarifa muhimu",
      "crop_title": "Chagua mazao yako",
      "nutrient_quantities": "Kiasi cha virutubishi",
      "nitrogen": "Nitrojeni (N) katika kilo/ha",
      "phosphorus": "Phosphorus (P) katika kilo/ha",
      "potassium": "Potassium (K) katika kilo/h",
      "plot_size": "Ukubwa wa ploti",
      "fertilizer_subtitle": "Ukubwa mdogo kuliko kitengo kimoja\nunaonyeshwa kama Mfano:\nnusu ya ekari = 0.5",
      "plot_size_label": "Ukubwa wa Plot (hekta)",
      "calculate": "Kokotoa",
      "view_history": "Tazama Historia",
      "calculation_history": "Historia ya Hesabu",
      "resource_1": "Kikokotoo\nCha\nMbolea",
      "resource_2": "Vidudu\nna\nMagonjwa",
      "resource_3": "Vidokezo\nvya Kilimo",
      "resource_4": "Tahadhari\nya wadudu\nna\nmagonjwa",
      "pest_and_diseases": "Wadudu na magonjwa",
      "disease_by_stage": "Ugonjwa kwa Hatua",
      "disease_subtitle": "Wadudu na magonjwa yote ambayo yanaweza\nkuonekana katika mazao yako\nkatika hatua tofauti",
      "seeding_stage": "Hatua ya Kuona",
      "see_more": "Tazama Zaidi",
      "vegetative_stage": "Hatua ya Mboga",
      "flowering_stage": "Hatua ya Maua",
      "fruiting_stage": "Hatua ya Matunda",
      "harvesting_stage": "Hatua ya Uvunaji",
      "pest_and_disease_alert": "Tahadhari ya wadudu na magonjwa",
      "pest_and_disease_alert_subtitle": "Kwa sasa, hakuna wadudu au magonjwa yaliyoripotiwa katika eneo lako.",
      "prevention_tips": "Vidokezo vya Kuzuia",
      "field_monitoring": "Ufuatiliaji wa Uga",
      "field_monitoring_subtitle": "Kukamata mapema na kuzuia kujenga-up ya wadudu mbaya katika shamba lako.",
      "learn_more": "Jifunze zaidi",
      "field_monitoring_description": "Ufuatiliaji wa shamba ni mazoezi bora zaidi ya kugundua magonjwa ya mimea katika hatua ya mapema. Kugundua magonjwa mapema kutakupa muda wa kutosha kuwazuia kuenea na kuharibu mazao yako zaidi.",
      "why_monitoring": "Kwa nini ufuatiliaji ni muhimu?",
      "monitoring_field_help": "Kufuatilia shamba lako mara kwa mara hukusaidia:",
      "help_1": "Kuokoa fedha kwa matibabu ya gharama kubwa.",
      "help_2": "Punguza hasara ya mavuno.",
      "info": "Wakulima ambao hufuatilia shamba lao mara kwa mara hufikia mavuno ya juu ya 50%.",
      "how_to_monitor": "Jinsi ya kufuatilia shamba lako:",
      "visit_your_field": "Tembelea uwanja wako",
      "how_1": "Tunapendekeza kufanya hivyo angalau\nmara mbili kwa wiki.",
      "check_several_spots": "Angalia matangazo kadhaa",
      "how_2": "Hakikisha uangalie angalau sehemu 5\ntofauti za shamba lako, kama\nkielelezo kinavyoonyesha hapa chini.",
      "step_3": "Tafuta mifumo isiyo ya kawaida\nna shughuli katika kila\nmoja ya maeneo haya",
      "how_3": "Zingatia rangi, deformation,\nuharibifu wa kulisha, na\nshughuli zingine za wadudu.",
      "carefully_examine_the_entire_crop": "Chunguza kwa makini mazao yote",
      "how_4": "Usisahau kuangalia majani\nkutoka pande zote mbili, shina, buds,\nmatunda, na shina.",
      "take_action_if_you_spot_something": "Chukua hatua ikiwa unaona kitu.",
      "take_action_subtitle": "Unapopata dalili za uvamizi, hakikisha kutumia kipengele chetu cha utambuzi wa mazao ili kutambua ugonjwa na kutibu kwa ufanisi.",
      "addition_description": "Kwa msaada zaidi, fikia Jumuiya ya Programu ya Kilimo au wasiliana na mshauri wako wa ndani anayeaminika.",
      "beans_disease_detection": "Utambuzi wa Magonjwa ya Maharage",
      "cassava_disease_detection": "Utambuzi wa Magonjwa ya Muhogo",
      "maize_disease_detection": "Utambuzi wa Magonjwa ya Mahindi",
      "rice_disease_detection": "Utambuzi wa Magonjwa ya Mpunga",
      "preventive_measures": "Hatua za kuzuia",
      "prediction": "Utabiri wa Magonjwa ya Mazao Kutumia Taarifa ya Hali ya Hewa",
      "report": "Ripoti",
   }
  };
}
