name: kilimo_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

#---------------- PACKAGES -------------------------------#
dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8

  # State Management
  provider: ^6.1.1
  path_provider: ^2.0.8
  shared_preferences:
  flutter_riverpod: ^2.4.10
  get: ^4.6.6
  get_storage: ^2.1.1
  localstorage: ^4.0.0+1

  # Firebase
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.0.10
  firebase_core: ^2.4.1
  firebase_messaging_platform_interface: ^4.2.10
  firebase_messaging: ^14.2.1

  # Tflite
  tflite_flutter: ^0.10.4
  # tflite: ^1.1.2
  tflite:
    git:
      url: https://github.com/Despicable-Us/tflite_flutter.git

  
  # Utility Packages
  http: ^1.1.0
  flutter_image_compress: ^2.1.0
  cached_network_image: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  backdrop: ^0.9.1
  badges: ^3.1.2
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.3.0
  multi_image_picker2: ^5.0.2
  image_picker: ^1.0.7
  collection: ^1.16.0
  image: ^4.1.7
  toast: ^0.3.0
  fluttertoast: ^8.0.7
  mailer: ^6.1.0
  getwidget: ^4.0.0
  mongo_dart: ^0.10.0
  weather: ^3.1.1
  location: ^5.0.3
  geolocator: ^11.0.0
  geocoding: ^2.0.4
  flutter_map: any
  geodesy: ^0.10.2
  latlong2: ^0.9.0
  google_sign_in: ^6.1.6
  url_launcher: ^6.0.0-nullsafety
  permission_handler: ^11.0.1
  animated_text_kit: ^4.2.1
  country_picker: ^2.0.8
  uuid: ^4.0.0
  share: ^2.0.4
  dio: ^5.4.1
  device_info: ^2.0.2
  carousel_slider: ^4.0.0
  flutter_dotenv: ^5.0.2
  flutter_map_marker_popup: ^6.1.2
  lat_lon_grid_plugin: ^0.2.2
  flutter_map_tappable_polyline: ^6.0.0
  mockito: ^5.4.4
  logging: ^1.2.0
  lottie: ^3.1.0
  logger: ^2.0.2+1
  intl: ^0.18.1
  flutter_native_splash: ^2.2.16
  smooth_page_indicator: ^1.1.0
  connectivity_plus: ^5.0.2
  flutter_rating_bar: ^4.0.1
  readmore: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_settings_screens: ^0.3.3-null-safety+2
  shimmer: ^3.0.0
  localize_and_translate: ^5.1.2
  flutter_translate: ^4.0.4
  firebase_app_check: ^0.2.2
  weather_icons: ^3.0.0
  realm: ^2.1.0
  flutter_markdown: ^0.7.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  date_format: ^2.0.7

#---------------- ./ PACKAGES END -------------------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  #---------------- LOCAL ASSETS --------------------------------#
  assets:
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/crops/
    - assets/images/categories/
    - assets/images/profile/
    - assets/images/weather/
    - assets/model/
    - assets/icons/
    - assets/logos/
    - assets/language/
    - assets/legal/

  #-------------------- LOCAL FONTS ------------------------------#
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/logos/splash-logo-white.png"
  min_sdk_android: 26
  remove_alpha_ios: true
  