// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnmOGGoM8OJoGMmEFUkjZg1TUK4FQOQEg',
    appId: '1:653462887527:web:f3de0780b7c204c45c48c2',
    messagingSenderId: '653462887527',
    projectId: 'kilimo-app-b5270',
    authDomain: 'kilimo-app-b5270.firebaseapp.com',
    storageBucket: 'kilimo-app-b5270.appspot.com',
    measurementId: 'G-B16W57035R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcjKHdpnrkoI8N6xSuZ0jsxCOn25R-yiI',
    appId: '1:653462887527:android:0b5b695336eaa8a55c48c2',
    messagingSenderId: '653462887527',
    projectId: 'kilimo-app-b5270',
    storageBucket: 'kilimo-app-b5270.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4NhDYIdePMyvllU8Kj03_a6w7cBwGNBo',
    appId: '1:653462887527:ios:937d2af8c29213305c48c2',
    messagingSenderId: '653462887527',
    projectId: 'kilimo-app-b5270',
    storageBucket: 'kilimo-app-b5270.appspot.com',
    androidClientId: '653462887527-1t04c0hnqvgh86ofnc162223pchkfslh.apps.googleusercontent.com',
    iosClientId: '653462887527-311jfboeuas5o1skspr95lgfakdh9c7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.kilimoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4NhDYIdePMyvllU8Kj03_a6w7cBwGNBo',
    appId: '1:653462887527:ios:45c842a8ff1fb3ac5c48c2',
    messagingSenderId: '653462887527',
    projectId: 'kilimo-app-b5270',
    storageBucket: 'kilimo-app-b5270.appspot.com',
    androidClientId: '653462887527-1t04c0hnqvgh86ofnc162223pchkfslh.apps.googleusercontent.com',
    iosClientId: '653462887527-jti1o6tu5nfaogku381pt1q79ql3ese6.apps.googleusercontent.com',
    iosBundleId: 'com.example.kilimoApp.RunnerTests',
  );
}
