// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUBaR6x2bLRLiHZ_3ljcZgThYhazn1uOw',
    appId: '1:904681071274:web:40019eb6f0eaef531466d3',
    messagingSenderId: '904681071274',
    projectId: 'kilimoapp-107fb',
    authDomain: 'kilimoapp-107fb.firebaseapp.com',
    storageBucket: 'kilimoapp-107fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs-imtqQgHO9itBsix5rVh9eR4xRdAUng',
    appId: '1:904681071274:android:a4893f64740c24e11466d3',
    messagingSenderId: '904681071274',
    projectId: 'kilimoapp-107fb',
    storageBucket: 'kilimoapp-107fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtttjG8qnlWAunnDVB2yVUC0EMCl2E3bI',
    appId: '1:904681071274:ios:572eeb551545399a1466d3',
    messagingSenderId: '904681071274',
    projectId: 'kilimoapp-107fb',
    storageBucket: 'kilimoapp-107fb.appspot.com',
    androidClientId: '904681071274-akj25u712e7vu98sg6dtjs6d5k36h34a.apps.googleusercontent.com',
    iosClientId: '904681071274-m2b6tun3n5pqa43hfe1c4qk1vs5rpgjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.kilimoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtttjG8qnlWAunnDVB2yVUC0EMCl2E3bI',
    appId: '1:904681071274:ios:572eeb551545399a1466d3',
    messagingSenderId: '904681071274',
    projectId: 'kilimoapp-107fb',
    storageBucket: 'kilimoapp-107fb.appspot.com',
    androidClientId: '904681071274-akj25u712e7vu98sg6dtjs6d5k36h34a.apps.googleusercontent.com',
    iosClientId: '904681071274-m2b6tun3n5pqa43hfe1c4qk1vs5rpgjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.kilimoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUBaR6x2bLRLiHZ_3ljcZgThYhazn1uOw',
    appId: '1:904681071274:web:7cbddf521d8ac5701466d3',
    messagingSenderId: '904681071274',
    projectId: 'kilimoapp-107fb',
    authDomain: 'kilimoapp-107fb.firebaseapp.com',
    storageBucket: 'kilimoapp-107fb.appspot.com',
  );

}